homepage:
  path: /
  defaults: { _controller: 'AppBundle:Default:index' }

project:
  prefix: /project
  resource: '@AppBundle/Resources/config/routing/project.yml'

comment:
  prefix: /comment
  resource: '@AppBundle/Resources/config/routing/comment.yml'