project_index:
  path: /
  defaults: { _controller: 'AppBundle:Project:index' }

project_create:
  path: /create
  defaults: { _controller: 'AppBundle:ManageProject:create' }

project_manage:
  path: /manage/{id}
  defaults: { _controller: 'AppBundle:ManageProject:manage' }

project_manage_update_ajax:
  path: /manage/{id}/update-xhr
  defaults: { _controller: 'AppBundle:ManageProject:updateAjax' }

project_add_participant:
  path: /manage/{id}/participant/add
  defaults: { _controller: 'AppBundle:ManageProject:addParticipant' }


project_read:
  path: /read/{id}
  defaults: { _controller: 'AppBundle:ReadProject:read' }

project_participate:
  path: /participate/{slug}
  defaults: { _controller: 'AppBundle:ReadProject:participate' }

project_participant_accepte:
  path: /participate/{slug}/accepte
  defaults: { _controller: 'AppBundle:ReadProject:choice', choice: 1 }

project_participant_decline:
  path: /participate/{slug}/decline
  defaults: { _controller: 'AppBundle:ReadProject:choice', choice: 2 }

project_participant_maybe:
  path: /participate/{slug}/maybe
  defaults: { _controller: 'AppBundle:ReadProject:choice', choice: 3 }