app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /
user_debug:
    resource: '@UserBundle/Resources/config/routing.yml'
    prefix: /debug

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#MediaBundle
cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"