<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $orderBy
     *
     * @return array
     */
    public function findAllOrderBy(array $orderBy)
    {
        $alias = 'baserepository';
        $qb = $this->createQueryBuilder($alias);
        foreach ($orderBy as $field => $type) {
            $qb->addOrderBy(sprintf('%s.%s', $alias, $field), $type);
        }
        return $qb->getQuery()->getResult();
    }
}
