<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends \Doctrine\ORM\EntityRepository
{
    const BASE_REPOSITORY_ALIAS = 'baserepository';
    const BASE_REPOSITORY_DELETE_ENTITY_ALIAS = 'deleteentity';
    /**
     * @param array $orderBy
     *
     * @return array
     */
    public function findAllOrderBy(array $orderBy)
    {
        $qb = $this->createQueryBuilder(self::BASE_REPOSITORY_ALIAS);
        foreach ($orderBy as $field => $type) {
            $qb->addOrderBy(sprintf('%s.%s', self::BASE_REPOSITORY_ALIAS, $field), $type);
        }
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $entity
     *
     * @return array
     */
    public function remove($entity)
    {
        $qb = $this->createQueryBuilder(self::BASE_REPOSITORY_ALIAS);
        $qb
            ->delete(get_class($entity), self::BASE_REPOSITORY_DELETE_ENTITY_ALIAS)
            ->where(self::BASE_REPOSITORY_DELETE_ENTITY_ALIAS . ' = :entity')
            ->setParameter('entity', $entity)
        ;
        return $qb->getQuery()->getResult();
    }
}
