<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Participant;
use AppBundle\Entity\Project;
use AppBundle\Entity\User;
use Doctrine\ORM\Query;
use Doctrine\ORM\Query\Expr;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends BaseRepository
{

    /**
     * @param User|null $excludeUser
     * @param array     $orderBy
     *
     * @return array
     */
    public function findPublicExcludeUser(User $excludeUser = null, $orderBy = [])
    {
        return $this->findProjectByContextAndExcludeUserQuery(Project::CONTEXT_PUBLIC, $excludeUser, $orderBy)->getQuery()->getResult();
    }

    /**
     * @param User|null $excludeUser
     * @param array     $orderBy
     *
     * @return array
     */
    public function findPrivateExcludeUser(User $excludeUser = null, $orderBy = [])
    {
        $alias = 'p';
        $qb = $this->findProjectByContextAndExcludeUserQuery(Project::CONTEXT_PRIVATE, $excludeUser, $orderBy, $alias);

        if (! $excludeUser->isAdmin()) {
            $qb
                ->join(Participant::class, 'par', Expr\Join::WITH,
                    "$alias.id=par.project")
                ->andWhere(
                    $qb->expr()->eq('par.user', ':userParticipant')
                )
                ->setParameter('userParticipant', $excludeUser->getId());
        }
        return $qb->getQuery()->getResult();
    }

    /**
     * @param      $context
     * @param User $excludeUser
     * @param      $orderBy
     * @param      $alias
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function findProjectByContextAndExcludeUserQuery($context, User $excludeUser, $orderBy, $alias = 'p')
    {
        $qb = $this->createQueryBuilder($alias);
        $qb
            ->where(
                $qb->expr()->eq($alias . '.context', ':context')
            )
            ->setParameter('context', $context)
        ;
        if ($excludeUser) {
            $qb
                ->andWhere(
                    $qb->expr()->neq($alias . '.creator', ':user')
                )
                ->setParameter('user', $excludeUser->getId())
            ;
        }

        foreach ($orderBy as $sort => $order) {
            $qb->addOrderBy($alias . '.' . $sort, $order);
        }
        return $qb;
    }
}
